name: Mirror Website

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write   # ⬅️ 给 GITHUB_TOKEN 写权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install wget
        run: sudo apt-get install -y wget

      - name: Mirror site
        run: |
          rm -rf docs
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://junpyomaygem.carrd.co/ -P docs
          mv docs/junpyomaygem.carrd.co/* docs/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
